name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
env:
  rendered_dist: 'tests-template/core-dist/'
  test_dist: 'tests/suite_qiime2_mystery-stew'
  report_html: 'tests/tool_test_output.html'
  report_json: 'tests/tool_test_output.json'

jobs:
  test-against-galaxy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.planemo/
        key: days-since-accident-0

    - name: install QIIME 2 core distro
      run: |
        envFile=qiime2-latest-py36-linux-conda.yml
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/$envFile
        conda env create -q -p ../test-env --file $envFile

    - name: install dependencies
      shell: bash -l {0}
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate ../test-env
        conda install -c https://packages.qiime2.org/qiime2/unverified/ -c conda-forge -c bioconda -c defaults q2-mystery-stew
        pip install planemo
        make dev

    - name: template all
      id: template_all
      shell: bash -l {0}
      continue-on-error: true
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate ../test-env
        mkdir -p ${{ env.rendered_dist }}
        q2galaxy template all ${{ env.rendered_dist }}

    # IF template all
    - name: publish template all
      if: steps.template_all.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: template-all
        path: ${{ env.rendered_dist }}
    # END IF

    - name: make test
      id: make_test
      shell: bash -l {0}
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate ../test-env
        make test

    # IF make test
    - name: rendered mystery-stew
      uses: actions/upload-artifact@v2
      if: steps.make_test.outcome == 'success'
      with:
        name: mystery-stew
        path: ${{ env.test_dist }}
    - name: html report
      uses: actions/upload-artifact@v2
      if: steps.make_test.outcome == 'success'
      with:
        name: html-report
        path: ${{ env.report_html }}
    - name: json report
      uses: actions/upload-artifact@v2
      if: steps.make_test.outcome == 'success'
      with:
        name: json-report
        path: ${{ env.report_json }}
      # END IF

    - name: Check for failure
      if: steps.template_all.outcome == 'failure'
      run: exit 1
